conda-forge/airflow-feedstock

- .travis.yml
- ci_support/run_docker_build.sh
- recipe/meta.yaml
I've been running Airflow successfully on Python 3 for awhile, so it seems reasonable to see if we can get this recipe working for it.
> Initial support for Python 3

- recipe/meta.yaml
Checklist
I've attempted to update the dependencies, following changes in `setup.py` seen here:
https://github.com/apache/airflow/compare/1.10.1...apache:1.10.3#diff-2eeaed663bd0d25b7e608891384b7298
closes #25
> 1.10.3 update dependencies

- recipe/meta.yaml
> Build 1.10.3 with python 3.7 support

- recipe/meta.yaml
This reverts commit 9851fbb1395352301a674bd154f7e73df3a69510.
Checklist
> Revert previous accidental commit

- recipe/meta.yaml
> Update pandas pins

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_python3.6.____cpython.yaml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.6.____cpython.yaml
- .ci_support/osx_64_python3.7.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- LICENSE.txt
- README.md
- recipe/install_airflow.sh
- recipe/meta.yaml
> Add compile_assets to the build

- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- recipe/meta.yaml
> Update to 1.10.15

- recipe/0002-remove-import-resources-py39.patch
- recipe/meta.yaml
> Update to 2.1.2

- recipe/meta.yaml
> Update to v2.1.3

- recipe/meta.yaml
> Update to v2.1.4

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- build-locally.py
- recipe/meta.yaml
> Update to 2.2.1

- .gitattributes
- README.md
- build-locally.py
- recipe/meta.yaml
> Update to v2.2.2

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_python3.7.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/meta.yaml
> Update to v2.2.3

- recipe/meta.yaml
> Update to v2.3.1

- .circleci/config.yml
- recipe/meta.yaml
> Update to 2.3.2

- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- build-locally.py
- recipe/meta.yaml
> Update to v2.3.3

- recipe/meta.yaml
Checklist
* Reset the build number to `0` (if the version changed)
closes #89
> Allow airflow-with-dask for python 3.9 and 3.10

- .azure-pipelines/azure-pipelines-osx.yml
- recipe/meta.yaml
> Update to v2.3.4

- recipe/meta.yaml
> Update to v2.4.0

- recipe/meta.yaml
> Update to v2.4.1

- recipe/meta.yaml
> Update to v2.4.2

- recipe/meta.yaml
> Update to v2.5.0

- recipe/meta.yaml
> Update to 2.5.1

- recipe/meta.yaml
> Update to 2.5.2

- recipe/meta.yaml
> Update to airflow 2.5.3

- recipe/meta.yaml
> Update to v2.6.0

- recipe/meta.yaml
> Update to v2.6.1

- recipe/meta.yaml
> Update to v2.6.2

- .scripts/run_osx_build.sh
- recipe/meta.yaml
> Update to v2.6.3

- .azure-pipelines/azure-pipelines-linux.yml
- recipe/meta.yaml
> Update to v2.7.0

- recipe/meta.yaml
> Update to v2.7.1

- recipe/meta.yaml
> Update to v2.7.3

- .ci_support/linux_64_python3.10.____cpython.yaml
- .ci_support/linux_64_python3.11.____cpython.yaml
- .ci_support/linux_64_python3.12.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.10.____cpython.yaml
- .ci_support/linux_aarch64_python3.11.____cpython.yaml
- .ci_support/linux_aarch64_python3.12.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_python3.11.____cpython.yaml
- .ci_support/linux_ppc64le_python3.12.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.10.____cpython.yaml
- .ci_support/osx_64_python3.11.____cpython.yaml
- .ci_support/osx_64_python3.12.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.10.____cpython.yaml
- .ci_support/osx_arm64_python3.11.____cpython.yaml
- .ci_support/osx_arm64_python3.12.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- build-locally.py
- recipe/meta.yaml
> Update to v2.8.2

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_python3.10.____cpython.yaml
- .ci_support/linux_64_python3.11.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.10.____cpython.yaml
- .ci_support/linux_aarch64_python3.11.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_python3.11.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.10.____cpython.yaml
- .ci_support/osx_64_python3.11.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.10.____cpython.yaml
- .ci_support/osx_arm64_python3.11.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- conda-forge.yml
- recipe/meta.yaml
> Update to v2.8.4

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_python3.12.____cpython.yaml
- .ci_support/linux_aarch64_python3.12.____cpython.yaml
- .ci_support/linux_ppc64le_python3.12.____cpython.yaml
- .ci_support/osx_64_python3.12.____cpython.yaml
- .ci_support/osx_arm64_python3.12.____cpython.yaml
- README.md
- recipe/install_airflow.sh
- recipe/meta.yaml
> Update to v2.9.0

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_python3.10.____cpython.yaml
- .ci_support/linux_64_python3.11.____cpython.yaml
- .ci_support/linux_64_python3.12.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .ci_support/linux_aarch64_python3.10.____cpython.yaml
- .ci_support/linux_aarch64_python3.11.____cpython.yaml
- .ci_support/linux_aarch64_python3.12.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_python3.11.____cpython.yaml
- .ci_support/linux_ppc64le_python3.12.____cpython.yaml
- .ci_support/linux_ppc64le_python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.10.____cpython.yaml
- .ci_support/osx_64_python3.11.____cpython.yaml
- .ci_support/osx_64_python3.12.____cpython.yaml
- .ci_support/osx_64_python3.8.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.10.____cpython.yaml
- .ci_support/osx_arm64_python3.11.____cpython.yaml
- .ci_support/osx_arm64_python3.12.____cpython.yaml
- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- recipe/meta.yaml
> Update to v2.9.1

- .ci_support/linux_64_python3.10.____cpython.yaml
- .ci_support/linux_64_python3.11.____cpython.yaml
- .ci_support/linux_64_python3.12.____cpython.yaml
- .ci_support/linux_64_python3.8.____cpython.yaml
- .ci_support/linux_64_python3.9.____cpython.yaml
- .scripts/build_steps.sh
- recipe/meta.yaml
> Update to apache-airflow v2.9.3

- recipe/meta.yaml
> Switch back to max_pin rather than exact for extras

- .ci_support/linux_aarch64_python3.10.____cpython.yaml
- .ci_support/linux_aarch64_python3.11.____cpython.yaml
- .ci_support/linux_aarch64_python3.12.____cpython.yaml
- .ci_support/linux_aarch64_python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_python3.11.____cpython.yaml
- .ci_support/linux_ppc64le_python3.12.____cpython.yaml
- .ci_support/linux_ppc64le_python3.9.____cpython.yaml
- .ci_support/osx_64_python3.10.____cpython.yaml
- .ci_support/osx_64_python3.11.____cpython.yaml
- .ci_support/osx_64_python3.12.____cpython.yaml
- .ci_support/osx_64_python3.9.____cpython.yaml
- .ci_support/osx_arm64_python3.10.____cpython.yaml
- .ci_support/osx_arm64_python3.11.____cpython.yaml
- .ci_support/osx_arm64_python3.12.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- .gitignore
- recipe/meta.yaml
> Update to v2.10.5
